services:
  database:
    build:
      context: .
      dockerfile: ./database/timescale/Dockerfile
    container_name: timescale-micromanager
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: micromanager
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d micromanager"]
      interval: 10s
      timeout: 5s
      retries: 10

  grafana-db:
    image: postgres:16-alpine
    container_name: grafana-postgres
    restart: always
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana -d grafana"]
      interval: 10s
      timeout: 5s
      retries: 10

  grafana:
    build:
      context: .
      dockerfile: ./grafana/Dockerfile
    container_name: grafana
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      grafana-db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3000:3000"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: grafana-db:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
      GF_DATABASE_SSL_MODE: disable
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning