apiVersion: 1

datasources:
  - name: Micromanager data source
    type: postgres
    access: proxy
    orgId: 1
    uid: aepqym6ihryf4e
    url: database:5432
    user: root
    database: micromanager
    secureJsonData:
      password: root
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400